FROM python:3.7 AS build
WORKDIR /application
COPY builder.py ./
COPY resources ./resources
COPY assets ./assets
RUN mkdir -p ./public/data

ARG MAPBOX_API_KEY
ARG MAPBOX_STYLE_URL
ARG MAP_DEFAULT_CENTER_LATITUDE
ARG MAP_DEFAULT_CENTER_LONGITUDE
ARG MAP_DEFAULT_ZOOM_LEVEL
ARG START_POINTS_RADIUS_LIMIT

ENV MAPBOX_API_KEY=$MAPBOX_API_KEY
ENV MAPBOX_STYLE_URL=$MAPBOX_STYLE_URL
ENV MAP_DEFAULT_CENTER_LATITUDE=$MAP_DEFAULT_CENTER_LATITUDE
RUN echo $MAP_DEFAULT_CENTER_LATITUDE
ENV MAP_DEFAULT_CENTER_LONGITUDE=$MAP_DEFAULT_CENTER_LONGITUDE
ENV MAP_DEFAULT_ZOOM_LEVEL=$MAP_DEFAULT_ZOOM_LEVEL
ENV START_POINTS_RADIUS_LIMIT=$START_POINTS_RADIUS_LIMIT

RUN python builder.py

FROM nginx:stable AS runtime
COPY --from=build /application/public /usr/share/nginx/html

